package com.wangcai.member.base.vo;

import com.wangcai.common.db.NSID;
import org.springframework.security.access.ConfigAttribute;

import java.io.Serializable;
import java.util.Collection;

public class MemUrlResource implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEM_BASE_URLRESOURCE.ID
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    @NSID
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEM_BASE_URLRESOURCE.URL
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEM_BASE_URLRESOURCE.URLDESC
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    private String urldesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEM_BASE_URLRESOURCE.ENABLE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    private Integer enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEM_BASE_URLRESOURCE.URLNAME
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    private String urlname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEM_BASE_URLRESOURCE.METTHODNAME
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    private String metthodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEM_BASE_URLRESOURCE.PARENTID
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    private Long parentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEM_BASE_URLRESOURCE.ID
     *
     * @return the value of MEM_BASE_URLRESOURCE.ID
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEM_BASE_URLRESOURCE.ID
     *
     * @param id the value for MEM_BASE_URLRESOURCE.ID
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEM_BASE_URLRESOURCE.URL
     *
     * @return the value of MEM_BASE_URLRESOURCE.URL
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEM_BASE_URLRESOURCE.URL
     *
     * @param url the value for MEM_BASE_URLRESOURCE.URL
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEM_BASE_URLRESOURCE.URLDESC
     *
     * @return the value of MEM_BASE_URLRESOURCE.URLDESC
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public String getUrldesc() {
        return urldesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEM_BASE_URLRESOURCE.URLDESC
     *
     * @param urldesc the value for MEM_BASE_URLRESOURCE.URLDESC
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public void setUrldesc(String urldesc) {
        this.urldesc = urldesc == null ? null : urldesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEM_BASE_URLRESOURCE.ENABLE
     *
     * @return the value of MEM_BASE_URLRESOURCE.ENABLE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEM_BASE_URLRESOURCE.ENABLE
     *
     * @param enable the value for MEM_BASE_URLRESOURCE.ENABLE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEM_BASE_URLRESOURCE.URLNAME
     *
     * @return the value of MEM_BASE_URLRESOURCE.URLNAME
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public String getUrlname() {
        return urlname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEM_BASE_URLRESOURCE.URLNAME
     *
     * @param urlname the value for MEM_BASE_URLRESOURCE.URLNAME
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public void setUrlname(String urlname) {
        this.urlname = urlname == null ? null : urlname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEM_BASE_URLRESOURCE.METTHODNAME
     *
     * @return the value of MEM_BASE_URLRESOURCE.METTHODNAME
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public String getMetthodname() {
        return metthodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEM_BASE_URLRESOURCE.METTHODNAME
     *
     * @param metthodname the value for MEM_BASE_URLRESOURCE.METTHODNAME
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public void setMetthodname(String metthodname) {
        this.metthodname = metthodname == null ? null : metthodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEM_BASE_URLRESOURCE.PARENTID
     *
     * @return the value of MEM_BASE_URLRESOURCE.PARENTID
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEM_BASE_URLRESOURCE.PARENTID
     *
     * @param parentid the value for MEM_BASE_URLRESOURCE.PARENTID
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    private Collection<ConfigAttribute> configAttributes;
    public void setConfigAttributes(Collection<ConfigAttribute> configAttributes) {
        this.configAttributes = configAttributes;
    }

    public Collection<ConfigAttribute> getConfigAttributes() {
        return configAttributes;
    }
}