package com.wangcai.member.base.vo;

public class MemUserRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEM_BASE_USERROLE.ROLEID
     *
     * @mbggenerated Wed Apr 01 17:03:20 CST 2015
     */
    private Long roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEM_BASE_USERROLE.USERID
     *
     * @mbggenerated Wed Apr 01 17:03:20 CST 2015
     */
    private Long userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEM_BASE_USERROLE.ROLEID
     *
     * @return the value of MEM_BASE_USERROLE.ROLEID
     *
     * @mbggenerated Wed Apr 01 17:03:20 CST 2015
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEM_BASE_USERROLE.ROLEID
     *
     * @param roleid the value for MEM_BASE_USERROLE.ROLEID
     *
     * @mbggenerated Wed Apr 01 17:03:20 CST 2015
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEM_BASE_USERROLE.USERID
     *
     * @return the value of MEM_BASE_USERROLE.USERID
     *
     * @mbggenerated Wed Apr 01 17:03:20 CST 2015
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEM_BASE_USERROLE.USERID
     *
     * @param userid the value for MEM_BASE_USERROLE.USERID
     *
     * @mbggenerated Wed Apr 01 17:03:20 CST 2015
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }
}