package com.wangcai.member.base.vo;

import com.wangcai.common.web.Page;
import java.util.ArrayList;
import java.util.List;

public class MemUrlResourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public MemUrlResourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public int getLimitStart() {
        if(this.page==null) {return -1;} else {return this.page.getLimitStart();}
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public int getLimitEnd() {
        if(this.page==null) {return -1;} else {return this.page.getLimitEnd();}
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("URL is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("URL is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("URL =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("URL <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("URL >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("URL >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("URL <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("URL <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("URL like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("URL not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("URL in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("URL not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("URL between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("URL not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrldescIsNull() {
            addCriterion("URLDESC is null");
            return (Criteria) this;
        }

        public Criteria andUrldescIsNotNull() {
            addCriterion("URLDESC is not null");
            return (Criteria) this;
        }

        public Criteria andUrldescEqualTo(String value) {
            addCriterion("URLDESC =", value, "urldesc");
            return (Criteria) this;
        }

        public Criteria andUrldescNotEqualTo(String value) {
            addCriterion("URLDESC <>", value, "urldesc");
            return (Criteria) this;
        }

        public Criteria andUrldescGreaterThan(String value) {
            addCriterion("URLDESC >", value, "urldesc");
            return (Criteria) this;
        }

        public Criteria andUrldescGreaterThanOrEqualTo(String value) {
            addCriterion("URLDESC >=", value, "urldesc");
            return (Criteria) this;
        }

        public Criteria andUrldescLessThan(String value) {
            addCriterion("URLDESC <", value, "urldesc");
            return (Criteria) this;
        }

        public Criteria andUrldescLessThanOrEqualTo(String value) {
            addCriterion("URLDESC <=", value, "urldesc");
            return (Criteria) this;
        }

        public Criteria andUrldescLike(String value) {
            addCriterion("URLDESC like", value, "urldesc");
            return (Criteria) this;
        }

        public Criteria andUrldescNotLike(String value) {
            addCriterion("URLDESC not like", value, "urldesc");
            return (Criteria) this;
        }

        public Criteria andUrldescIn(List<String> values) {
            addCriterion("URLDESC in", values, "urldesc");
            return (Criteria) this;
        }

        public Criteria andUrldescNotIn(List<String> values) {
            addCriterion("URLDESC not in", values, "urldesc");
            return (Criteria) this;
        }

        public Criteria andUrldescBetween(String value1, String value2) {
            addCriterion("URLDESC between", value1, value2, "urldesc");
            return (Criteria) this;
        }

        public Criteria andUrldescNotBetween(String value1, String value2) {
            addCriterion("URLDESC not between", value1, value2, "urldesc");
            return (Criteria) this;
        }

        public Criteria andEnableIsNull() {
            addCriterion("ENABLE is null");
            return (Criteria) this;
        }

        public Criteria andEnableIsNotNull() {
            addCriterion("ENABLE is not null");
            return (Criteria) this;
        }

        public Criteria andEnableEqualTo(Integer value) {
            addCriterion("ENABLE =", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotEqualTo(Integer value) {
            addCriterion("ENABLE <>", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThan(Integer value) {
            addCriterion("ENABLE >", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThanOrEqualTo(Integer value) {
            addCriterion("ENABLE >=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThan(Integer value) {
            addCriterion("ENABLE <", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThanOrEqualTo(Integer value) {
            addCriterion("ENABLE <=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableIn(List<Integer> values) {
            addCriterion("ENABLE in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotIn(List<Integer> values) {
            addCriterion("ENABLE not in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableBetween(Integer value1, Integer value2) {
            addCriterion("ENABLE between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotBetween(Integer value1, Integer value2) {
            addCriterion("ENABLE not between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andUrlnameIsNull() {
            addCriterion("URLNAME is null");
            return (Criteria) this;
        }

        public Criteria andUrlnameIsNotNull() {
            addCriterion("URLNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUrlnameEqualTo(String value) {
            addCriterion("URLNAME =", value, "urlname");
            return (Criteria) this;
        }

        public Criteria andUrlnameNotEqualTo(String value) {
            addCriterion("URLNAME <>", value, "urlname");
            return (Criteria) this;
        }

        public Criteria andUrlnameGreaterThan(String value) {
            addCriterion("URLNAME >", value, "urlname");
            return (Criteria) this;
        }

        public Criteria andUrlnameGreaterThanOrEqualTo(String value) {
            addCriterion("URLNAME >=", value, "urlname");
            return (Criteria) this;
        }

        public Criteria andUrlnameLessThan(String value) {
            addCriterion("URLNAME <", value, "urlname");
            return (Criteria) this;
        }

        public Criteria andUrlnameLessThanOrEqualTo(String value) {
            addCriterion("URLNAME <=", value, "urlname");
            return (Criteria) this;
        }

        public Criteria andUrlnameLike(String value) {
            addCriterion("URLNAME like", value, "urlname");
            return (Criteria) this;
        }

        public Criteria andUrlnameNotLike(String value) {
            addCriterion("URLNAME not like", value, "urlname");
            return (Criteria) this;
        }

        public Criteria andUrlnameIn(List<String> values) {
            addCriterion("URLNAME in", values, "urlname");
            return (Criteria) this;
        }

        public Criteria andUrlnameNotIn(List<String> values) {
            addCriterion("URLNAME not in", values, "urlname");
            return (Criteria) this;
        }

        public Criteria andUrlnameBetween(String value1, String value2) {
            addCriterion("URLNAME between", value1, value2, "urlname");
            return (Criteria) this;
        }

        public Criteria andUrlnameNotBetween(String value1, String value2) {
            addCriterion("URLNAME not between", value1, value2, "urlname");
            return (Criteria) this;
        }

        public Criteria andMetthodnameIsNull() {
            addCriterion("METTHODNAME is null");
            return (Criteria) this;
        }

        public Criteria andMetthodnameIsNotNull() {
            addCriterion("METTHODNAME is not null");
            return (Criteria) this;
        }

        public Criteria andMetthodnameEqualTo(String value) {
            addCriterion("METTHODNAME =", value, "metthodname");
            return (Criteria) this;
        }

        public Criteria andMetthodnameNotEqualTo(String value) {
            addCriterion("METTHODNAME <>", value, "metthodname");
            return (Criteria) this;
        }

        public Criteria andMetthodnameGreaterThan(String value) {
            addCriterion("METTHODNAME >", value, "metthodname");
            return (Criteria) this;
        }

        public Criteria andMetthodnameGreaterThanOrEqualTo(String value) {
            addCriterion("METTHODNAME >=", value, "metthodname");
            return (Criteria) this;
        }

        public Criteria andMetthodnameLessThan(String value) {
            addCriterion("METTHODNAME <", value, "metthodname");
            return (Criteria) this;
        }

        public Criteria andMetthodnameLessThanOrEqualTo(String value) {
            addCriterion("METTHODNAME <=", value, "metthodname");
            return (Criteria) this;
        }

        public Criteria andMetthodnameLike(String value) {
            addCriterion("METTHODNAME like", value, "metthodname");
            return (Criteria) this;
        }

        public Criteria andMetthodnameNotLike(String value) {
            addCriterion("METTHODNAME not like", value, "metthodname");
            return (Criteria) this;
        }

        public Criteria andMetthodnameIn(List<String> values) {
            addCriterion("METTHODNAME in", values, "metthodname");
            return (Criteria) this;
        }

        public Criteria andMetthodnameNotIn(List<String> values) {
            addCriterion("METTHODNAME not in", values, "metthodname");
            return (Criteria) this;
        }

        public Criteria andMetthodnameBetween(String value1, String value2) {
            addCriterion("METTHODNAME between", value1, value2, "metthodname");
            return (Criteria) this;
        }

        public Criteria andMetthodnameNotBetween(String value1, String value2) {
            addCriterion("METTHODNAME not between", value1, value2, "metthodname");
            return (Criteria) this;
        }

        public Criteria andParentidIsNull() {
            addCriterion("PARENTID is null");
            return (Criteria) this;
        }

        public Criteria andParentidIsNotNull() {
            addCriterion("PARENTID is not null");
            return (Criteria) this;
        }

        public Criteria andParentidEqualTo(Long value) {
            addCriterion("PARENTID =", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotEqualTo(Long value) {
            addCriterion("PARENTID <>", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThan(Long value) {
            addCriterion("PARENTID >", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThanOrEqualTo(Long value) {
            addCriterion("PARENTID >=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThan(Long value) {
            addCriterion("PARENTID <", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThanOrEqualTo(Long value) {
            addCriterion("PARENTID <=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidIn(List<Long> values) {
            addCriterion("PARENTID in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotIn(List<Long> values) {
            addCriterion("PARENTID not in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidBetween(Long value1, Long value2) {
            addCriterion("PARENTID between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotBetween(Long value1, Long value2) {
            addCriterion("PARENTID not between", value1, value2, "parentid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 03 14:45:12 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}