package com.wangcai.member.base.vo;

public class MemUrlRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEM_BASE_URLROLE.ROLEID
     *
     * @mbggenerated Wed Apr 01 17:03:47 CST 2015
     */
    private Long roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEM_BASE_URLROLE.RESOURCEID
     *
     * @mbggenerated Wed Apr 01 17:03:47 CST 2015
     */
    private Long resourceid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEM_BASE_URLROLE.ROLEID
     *
     * @return the value of MEM_BASE_URLROLE.ROLEID
     *
     * @mbggenerated Wed Apr 01 17:03:47 CST 2015
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEM_BASE_URLROLE.ROLEID
     *
     * @param roleid the value for MEM_BASE_URLROLE.ROLEID
     *
     * @mbggenerated Wed Apr 01 17:03:47 CST 2015
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEM_BASE_URLROLE.RESOURCEID
     *
     * @return the value of MEM_BASE_URLROLE.RESOURCEID
     *
     * @mbggenerated Wed Apr 01 17:03:47 CST 2015
     */
    public Long getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEM_BASE_URLROLE.RESOURCEID
     *
     * @param resourceid the value for MEM_BASE_URLROLE.RESOURCEID
     *
     * @mbggenerated Wed Apr 01 17:03:47 CST 2015
     */
    public void setResourceid(Long resourceid) {
        this.resourceid = resourceid;
    }
}