package com.wangcai.member.member.vo;

import java.util.Date;
import java.util.Set;

import org.springframework.security.core.GrantedAuthority;


public class Member {
	public Member() {
		super();
	}

    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.CardNo
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String cardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.CardCode
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String cardcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.HandNo
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String handno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Name
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Sex
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.BirthDate
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Date birthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.IDCardType
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String idcardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.IDNumber
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String idnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Telephone
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Mobile
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.EmergencyPhone
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String emergencyphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Email
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.HomePage
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String homepage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Address
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.ZipCode
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.OpenDate
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Date opendate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.ValidateDate
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Date validatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Discount
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Double discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Balance
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Double balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Password
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.TotalPoints
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Integer totalpoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.TotalConsumption
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Double totalconsumption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.TotalRecharge
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Double totalrecharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.TotalCount
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Integer totalcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.MaxCount
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Integer maxcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Portraint
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String portraint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.AttachGuID
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String attachguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Note
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Province
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.City
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.District
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Hometown
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String hometown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Nationality
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Creator
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.CreateTime
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Editor
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String editor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.EditTime
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Date edittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Dept_ID
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Company_ID
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Year
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Month
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Integer month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Introducer
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String introducer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.Position
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_ms_member.MemberState
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    private Integer memberstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.ID
     *
     * @return the value of ms_ms_member.ID
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.CardNo
     *
     * @return the value of ms_ms_member.CardNo
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.CardNo
     *
     * @param cardno the value for ms_ms_member.CardNo
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.CardCode
     *
     * @return the value of ms_ms_member.CardCode
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getCardcode() {
        return cardcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.CardCode
     *
     * @param cardcode the value for ms_ms_member.CardCode
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setCardcode(String cardcode) {
        this.cardcode = cardcode == null ? null : cardcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.HandNo
     *
     * @return the value of ms_ms_member.HandNo
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getHandno() {
        return handno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.HandNo
     *
     * @param handno the value for ms_ms_member.HandNo
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setHandno(String handno) {
        this.handno = handno == null ? null : handno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Name
     *
     * @return the value of ms_ms_member.Name
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Name
     *
     * @param name the value for ms_ms_member.Name
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Sex
     *
     * @return the value of ms_ms_member.Sex
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Sex
     *
     * @param sex the value for ms_ms_member.Sex
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.BirthDate
     *
     * @return the value of ms_ms_member.BirthDate
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.BirthDate
     *
     * @param birthdate the value for ms_ms_member.BirthDate
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.IDCardType
     *
     * @return the value of ms_ms_member.IDCardType
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getIdcardtype() {
        return idcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.IDCardType
     *
     * @param idcardtype the value for ms_ms_member.IDCardType
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setIdcardtype(String idcardtype) {
        this.idcardtype = idcardtype == null ? null : idcardtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.IDNumber
     *
     * @return the value of ms_ms_member.IDNumber
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getIdnumber() {
        return idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.IDNumber
     *
     * @param idnumber the value for ms_ms_member.IDNumber
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber == null ? null : idnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Telephone
     *
     * @return the value of ms_ms_member.Telephone
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Telephone
     *
     * @param telephone the value for ms_ms_member.Telephone
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Mobile
     *
     * @return the value of ms_ms_member.Mobile
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Mobile
     *
     * @param mobile the value for ms_ms_member.Mobile
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.EmergencyPhone
     *
     * @return the value of ms_ms_member.EmergencyPhone
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getEmergencyphone() {
        return emergencyphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.EmergencyPhone
     *
     * @param emergencyphone the value for ms_ms_member.EmergencyPhone
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setEmergencyphone(String emergencyphone) {
        this.emergencyphone = emergencyphone == null ? null : emergencyphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Email
     *
     * @return the value of ms_ms_member.Email
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Email
     *
     * @param email the value for ms_ms_member.Email
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.HomePage
     *
     * @return the value of ms_ms_member.HomePage
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getHomepage() {
        return homepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.HomePage
     *
     * @param homepage the value for ms_ms_member.HomePage
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setHomepage(String homepage) {
        this.homepage = homepage == null ? null : homepage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Address
     *
     * @return the value of ms_ms_member.Address
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Address
     *
     * @param address the value for ms_ms_member.Address
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.ZipCode
     *
     * @return the value of ms_ms_member.ZipCode
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.ZipCode
     *
     * @param zipcode the value for ms_ms_member.ZipCode
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.OpenDate
     *
     * @return the value of ms_ms_member.OpenDate
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Date getOpendate() {
        return opendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.OpenDate
     *
     * @param opendate the value for ms_ms_member.OpenDate
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setOpendate(Date opendate) {
        this.opendate = opendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.ValidateDate
     *
     * @return the value of ms_ms_member.ValidateDate
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Date getValidatedate() {
        return validatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.ValidateDate
     *
     * @param validatedate the value for ms_ms_member.ValidateDate
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setValidatedate(Date validatedate) {
        this.validatedate = validatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Discount
     *
     * @return the value of ms_ms_member.Discount
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Discount
     *
     * @param discount the value for ms_ms_member.Discount
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Balance
     *
     * @return the value of ms_ms_member.Balance
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Balance
     *
     * @param balance the value for ms_ms_member.Balance
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Password
     *
     * @return the value of ms_ms_member.Password
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Password
     *
     * @param password the value for ms_ms_member.Password
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.TotalPoints
     *
     * @return the value of ms_ms_member.TotalPoints
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Integer getTotalpoints() {
        return totalpoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.TotalPoints
     *
     * @param totalpoints the value for ms_ms_member.TotalPoints
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setTotalpoints(Integer totalpoints) {
        this.totalpoints = totalpoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.TotalConsumption
     *
     * @return the value of ms_ms_member.TotalConsumption
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Double getTotalconsumption() {
        return totalconsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.TotalConsumption
     *
     * @param totalconsumption the value for ms_ms_member.TotalConsumption
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setTotalconsumption(Double totalconsumption) {
        this.totalconsumption = totalconsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.TotalRecharge
     *
     * @return the value of ms_ms_member.TotalRecharge
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Double getTotalrecharge() {
        return totalrecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.TotalRecharge
     *
     * @param totalrecharge the value for ms_ms_member.TotalRecharge
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setTotalrecharge(Double totalrecharge) {
        this.totalrecharge = totalrecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.TotalCount
     *
     * @return the value of ms_ms_member.TotalCount
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Integer getTotalcount() {
        return totalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.TotalCount
     *
     * @param totalcount the value for ms_ms_member.TotalCount
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setTotalcount(Integer totalcount) {
        this.totalcount = totalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.MaxCount
     *
     * @return the value of ms_ms_member.MaxCount
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Integer getMaxcount() {
        return maxcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.MaxCount
     *
     * @param maxcount the value for ms_ms_member.MaxCount
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setMaxcount(Integer maxcount) {
        this.maxcount = maxcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Portraint
     *
     * @return the value of ms_ms_member.Portraint
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getPortraint() {
        return portraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Portraint
     *
     * @param portraint the value for ms_ms_member.Portraint
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setPortraint(String portraint) {
        this.portraint = portraint == null ? null : portraint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.AttachGuID
     *
     * @return the value of ms_ms_member.AttachGuID
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getAttachguid() {
        return attachguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.AttachGuID
     *
     * @param attachguid the value for ms_ms_member.AttachGuID
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setAttachguid(String attachguid) {
        this.attachguid = attachguid == null ? null : attachguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Note
     *
     * @return the value of ms_ms_member.Note
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Note
     *
     * @param note the value for ms_ms_member.Note
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Province
     *
     * @return the value of ms_ms_member.Province
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Province
     *
     * @param province the value for ms_ms_member.Province
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.City
     *
     * @return the value of ms_ms_member.City
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.City
     *
     * @param city the value for ms_ms_member.City
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.District
     *
     * @return the value of ms_ms_member.District
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.District
     *
     * @param district the value for ms_ms_member.District
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Hometown
     *
     * @return the value of ms_ms_member.Hometown
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getHometown() {
        return hometown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Hometown
     *
     * @param hometown the value for ms_ms_member.Hometown
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setHometown(String hometown) {
        this.hometown = hometown == null ? null : hometown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Nationality
     *
     * @return the value of ms_ms_member.Nationality
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Nationality
     *
     * @param nationality the value for ms_ms_member.Nationality
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Creator
     *
     * @return the value of ms_ms_member.Creator
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Creator
     *
     * @param creator the value for ms_ms_member.Creator
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.CreateTime
     *
     * @return the value of ms_ms_member.CreateTime
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.CreateTime
     *
     * @param createtime the value for ms_ms_member.CreateTime
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Editor
     *
     * @return the value of ms_ms_member.Editor
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Editor
     *
     * @param editor the value for ms_ms_member.Editor
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.EditTime
     *
     * @return the value of ms_ms_member.EditTime
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Date getEdittime() {
        return edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.EditTime
     *
     * @param edittime the value for ms_ms_member.EditTime
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setEdittime(Date edittime) {
        this.edittime = edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Dept_ID
     *
     * @return the value of ms_ms_member.Dept_ID
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Dept_ID
     *
     * @param deptId the value for ms_ms_member.Dept_ID
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Company_ID
     *
     * @return the value of ms_ms_member.Company_ID
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Company_ID
     *
     * @param companyId the value for ms_ms_member.Company_ID
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Year
     *
     * @return the value of ms_ms_member.Year
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Year
     *
     * @param year the value for ms_ms_member.Year
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Month
     *
     * @return the value of ms_ms_member.Month
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Month
     *
     * @param month the value for ms_ms_member.Month
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Introducer
     *
     * @return the value of ms_ms_member.Introducer
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getIntroducer() {
        return introducer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Introducer
     *
     * @param introducer the value for ms_ms_member.Introducer
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setIntroducer(String introducer) {
        this.introducer = introducer == null ? null : introducer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.Position
     *
     * @return the value of ms_ms_member.Position
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.Position
     *
     * @param position the value for ms_ms_member.Position
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_ms_member.MemberState
     *
     * @return the value of ms_ms_member.MemberState
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public Integer getMemberstate() {
        return memberstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_ms_member.MemberState
     *
     * @param memberstate the value for ms_ms_member.MemberState
     *
     * @mbggenerated Thu Mar 26 23:55:11 CST 2015
     */
    public void setMemberstate(Integer memberstate) {
        this.memberstate = memberstate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}