package com.wangcai.member.base.dao;

import com.wangcai.member.base.vo.MemRole;
import com.wangcai.member.base.vo.MemRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_ROLE
     *
     * @mbggenerated Wed Apr 01 17:00:37 CST 2015
     */
    int countByExample(MemRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_ROLE
     *
     * @mbggenerated Wed Apr 01 17:00:37 CST 2015
     */
    int deleteByExample(MemRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_ROLE
     *
     * @mbggenerated Wed Apr 01 17:00:37 CST 2015
     */
    int deleteByPrimaryKey(Long roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_ROLE
     *
     * @mbggenerated Wed Apr 01 17:00:37 CST 2015
     */
    int insert(MemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_ROLE
     *
     * @mbggenerated Wed Apr 01 17:00:37 CST 2015
     */
    int insertSelective(MemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_ROLE
     *
     * @mbggenerated Wed Apr 01 17:00:37 CST 2015
     */
    List<MemRole> selectByExample(MemRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_ROLE
     *
     * @mbggenerated Wed Apr 01 17:00:37 CST 2015
     */
    MemRole selectByPrimaryKey(Long roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_ROLE
     *
     * @mbggenerated Wed Apr 01 17:00:37 CST 2015
     */
    int updateByExampleSelective(@Param("record") MemRole record, @Param("example") MemRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_ROLE
     *
     * @mbggenerated Wed Apr 01 17:00:37 CST 2015
     */
    int updateByExample(@Param("record") MemRole record, @Param("example") MemRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_ROLE
     *
     * @mbggenerated Wed Apr 01 17:00:37 CST 2015
     */
    int updateByPrimaryKeySelective(MemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_ROLE
     *
     * @mbggenerated Wed Apr 01 17:00:37 CST 2015
     */
    int updateByPrimaryKey(MemRole record);
}