package com.wangcai.member.base.dao;

import com.wangcai.member.base.vo.MemUserRoleExample;
import com.wangcai.member.base.vo.MemUserRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USERROLE
     *
     * @mbggenerated Wed Apr 01 17:03:20 CST 2015
     */
    int countByExample(MemUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USERROLE
     *
     * @mbggenerated Wed Apr 01 17:03:20 CST 2015
     */
    int deleteByExample(MemUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USERROLE
     *
     * @mbggenerated Wed Apr 01 17:03:20 CST 2015
     */
    int deleteByPrimaryKey(MemUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USERROLE
     *
     * @mbggenerated Wed Apr 01 17:03:20 CST 2015
     */
    int insert(MemUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USERROLE
     *
     * @mbggenerated Wed Apr 01 17:03:20 CST 2015
     */
    int insertSelective(MemUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USERROLE
     *
     * @mbggenerated Wed Apr 01 17:03:20 CST 2015
     */
    List<MemUserRoleKey> selectByExample(MemUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USERROLE
     *
     * @mbggenerated Wed Apr 01 17:03:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") MemUserRoleKey record, @Param("example") MemUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USERROLE
     *
     * @mbggenerated Wed Apr 01 17:03:20 CST 2015
     */
    int updateByExample(@Param("record") MemUserRoleKey record, @Param("example") MemUserRoleExample example);
}