package com.wangcai.member.base.dao;

import com.wangcai.member.base.vo.MemUser;
import com.wangcai.member.base.vo.MemUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USER
     *
     * @mbggenerated Wed Apr 01 16:59:03 CST 2015
     */
    int countByExample(MemUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USER
     *
     * @mbggenerated Wed Apr 01 16:59:03 CST 2015
     */
    int deleteByExample(MemUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USER
     *
     * @mbggenerated Wed Apr 01 16:59:03 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USER
     *
     * @mbggenerated Wed Apr 01 16:59:03 CST 2015
     */
    int insert(MemUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USER
     *
     * @mbggenerated Wed Apr 01 16:59:03 CST 2015
     */
    int insertSelective(MemUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USER
     *
     * @mbggenerated Wed Apr 01 16:59:03 CST 2015
     */
    List<MemUser> selectByExample(MemUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USER
     *
     * @mbggenerated Wed Apr 01 16:59:03 CST 2015
     */
    MemUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USER
     *
     * @mbggenerated Wed Apr 01 16:59:03 CST 2015
     */
    int updateByExampleSelective(@Param("record") MemUser record, @Param("example") MemUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USER
     *
     * @mbggenerated Wed Apr 01 16:59:03 CST 2015
     */
    int updateByExample(@Param("record") MemUser record, @Param("example") MemUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USER
     *
     * @mbggenerated Wed Apr 01 16:59:03 CST 2015
     */
    int updateByPrimaryKeySelective(MemUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_USER
     *
     * @mbggenerated Wed Apr 01 16:59:03 CST 2015
     */
    int updateByPrimaryKey(MemUser record);
}