package com.wangcai.member.base.dao;

import com.wangcai.member.base.vo.MemUrlResource;
import com.wangcai.member.base.vo.MemUrlResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemUrlResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    int countByExample(MemUrlResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    int deleteByExample(MemUrlResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    int insert(MemUrlResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    int insertSelective(MemUrlResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    List<MemUrlResource> selectByExample(MemUrlResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    MemUrlResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    int updateByExampleSelective(@Param("record") MemUrlResource record, @Param("example") MemUrlResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    int updateByExample(@Param("record") MemUrlResource record, @Param("example") MemUrlResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    int updateByPrimaryKeySelective(MemUrlResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEM_BASE_URLRESOURCE
     *
     * @mbggenerated Thu Dec 03 14:45:12 CST 2015
     */
    int updateByPrimaryKey(MemUrlResource record);
}